### ISSUE TITLE
Register and login user with github

### ISSUE THREAD

**Issue by djules75** [codersfield/candra#1]

**Comment by thimovss** [comment]
Github Login manually tested and was successful.
Step 1. Press Sign-in in the upper-right corner
![1](https://cloud.githubusercontent.com/assets/8835734/18078125/7660defa-6ebc-11e6-9537-c8e0990471f1.png)
Step 2. Click the blue "Sign in with Github" button.
![2](https://cloud.githubusercontent.com/assets/8835734/18078128/766c9c04-6ebc-11e6-9c9a-d83ddd64d38b.png)
Step 3. Click the green "Authorize application" button.
![3](https://cloud.githubusercontent.com/assets/8835734/18078126/76681b98-6ebc-11e6-89b4-1598b3ccc630.png)
Step 4. The user is signed in successfully.
![4](https://cloud.githubusercontent.com/assets/8835734/18078127/7669f846-6ebc-11e6-92a4-abce730ade1c.png)
