### ISSUE TITLE
Add a picture to user profile page

### ISSUE THREAD

**Issue by djules75** [codersfield/candra#3]

**Comment by thimovss** [comment]
Profile picture can now be changed in the admin panel.
![fireshot screen capture 028 - membership management system - localhost_3000_users_v47xdltdqwepmghtn_ed](https://cloud.githubusercontent.com/assets/8835734/18154048/15a6828a-7034-11e6-9abb-c2b15b6a5839.png)
![fireshot screen capture 029 - membership management system - localhost_3000_adm](https://cloud.githubusercontent.com/assets/8835734/18154046/159c5878-7034-11e6-881a-01eaddae6559.png)
![fireshot screen capture 030 - membership management system - localhost_3000_profi](https://cloud.githubusercontent.com/assets/8835734/18154045/159c6246-7034-11e6-84ec-183b6837f978.png)
![fireshot screen capture 031 - membership management system - localhost_3000_membe](https://cloud.githubusercontent.com/assets/8835734/18154047/159d5f70-7034-11e6-8040-68938b34fe63.png)
