### ISSUE TITLE
Move logging of spaceapi to a separate logging facility

### ISSUE THREAD

**Issue by rngadam** [codersfield/candra#30]
Log the errors somewhere else than on the main console at Meteor app startup.

**Comment by thimovss** [comment]
![fireshot screen capture 035 - membership management system - localhost_3000_admi](https://cloud.githubusercontent.com/assets/8835734/18344199/eaa052ae-75e8-11e6-8d85-9a25dcf15837.png)
![fireshot screen capture 036 - membership management system - localhost_3000_admi](https://cloud.githubusercontent.com/assets/8835734/18344201/ead7ca22-75e8-11e6-8bdc-1ed00aad077a.png)
